#!/bin/sh
exec tail -n +3 $0

menuentry "FreeBSD 13" --class freebsd --class bsd --class os {
 insmod ufs2
 insmod bsd
 set root=(hd2,gpt4)
 kfreebsd /boot/kernel/kernel
 kfreebsd_loadenv /boot/device.hints
 set kFreeBSD.vfs.root.mountfrom=ufs:/dev/ada1p4
 set kFreeBSD.vfs.root.mountfrom.options=rw
 set kFreeBSD.hw.psm.synaptics_support=1
}
